options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/tts-fastpi/collab-editor:$COMMIT_SHA', '.']

  - name: 'docker'
    args: ['push', 'gcr.io/tts-fastpi/collab-editor:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - collab-editor
      - --image
      - 'gcr.io/tts-fastpi/collab-editor:$COMMIT_SHA'
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --memory
      - 512Mi
      - --cpu
      - '1'
      - --max-instances
      - '10'

images:
  - 'gcr.io/tts-fastpi/collab-editor:$COMMIT_SHA'
